//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSW.CodeGeneration.Units.Definitions
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using WSW.CodeGeneration.Units.Definitions;
    
    
    public partial class USGallons : VolumeValue
    {
        
        protected USGallons(double value) : 
                base(value)
        {
        }
        
        public override string Suffix
        {
            get
            {
                return "USG";
            }
        }
        
protected override double Scalar => throw new NotImplementedException();
        
public static USGallons FromUSGallons(double value) => throw new NotImplementedException();
        
public static USGallons FromSI(double siValue) => throw new NotImplementedException();
    }
}
