//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSW.CodeGeneration.Units.Definitions
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using WSW.CodeGeneration.Units.Definitions;
    
    
    public abstract partial class VolumeValue : ValueWithUnit
    {
        
        public VolumeValue(double value) : 
                base(value)
        {
        }
        
        public static System.Collections.Generic.IEnumerable<string> UnitNames
        {
            get
            {
                yield return nameof(CubicMeters);
                yield return nameof(Liters);
                yield return nameof(USGallons);
            }
        }
        
        public override ValueWithUnit TryConvert(string unit)
        {
            if ((unit == "CubicMeters"))
            {
                return CubicMeters.FromSI(SIValue);
            }
            if ((unit == "Liters"))
            {
                return Liters.FromSI(SIValue);
            }
            if ((unit == "USGallons"))
            {
                return USGallons.FromSI(SIValue);
            }
            return null;
        }
        
        public static VolumeValue TryCreate(double value, string unit)
        {
            if ((unit == "CubicMeters"))
            {
                return CubicMeters.FromCubicMeters(value);
            }
            if ((unit == "Liters"))
            {
                return Liters.FromLiters(value);
            }
            if ((unit == "USGallons"))
            {
                return USGallons.FromUSGallons(value);
            }
            return null;
        }
    }
}
