//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSW.CodeGeneration.Units.Definitions
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using WSW.CodeGeneration.Units.Definitions;
    
    
    public abstract partial class LengthValue : ValueWithUnit
    {
        
        public LengthValue(double value) : 
                base(value)
        {
        }
        
        public static System.Collections.Generic.IEnumerable<string> UnitNames
        {
            get
            {
                yield return nameof(Meters);
                yield return nameof(Inches);
            }
        }
        
        public override ValueWithUnit TryConvert(string unit)
        {
            if ((unit == "Meters"))
            {
                return Meters.FromSI(SIValue);
            }
            if ((unit == "Inches"))
            {
                return Inches.FromSI(SIValue);
            }
            return null;
        }
        
        public static LengthValue TryCreate(double value, string unit)
        {
            if ((unit == "Meters"))
            {
                return Meters.FromMeters(value);
            }
            if ((unit == "Inches"))
            {
                return Inches.FromInches(value);
            }
            return null;
        }
    }
}
